/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import clases.FileCollection;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import clases.AlmacenVectorListener;
import components.TableActionCellEditor;
import components.TableActionCellRender;
import javax.swing.event.TableModelEvent;
import clases.TableEvent;
import components.CenterRender;
import components.FloatEditor;
import components.StringEditor;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author LENOVO
 */
public class Administrador extends javax.swing.JFrame {
    final String cocido="cocido.txt";
    final String animal="origen_animal.txt";
    final String refresco="refresco.txt";
    final String agua="aguas_jugos.txt";
    final String venta="venta.txt";
    final String provedor="provedor.txt";
    final String productos="productos.txt";
    final String compras="productos.txt";
    /**
     * Creates new form Administrador
     */
    public Administrador() 
    {           
        try 
        {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } 
        catch(Exception ex) 
        {
            System.err.println( "Failed to initialize LaF" );
        }
        
        initComponents();
        initProducto();
        tProducto.init(compras);
        tVenta.init(tVenta.getColumnModel().getColumnIndex("Subtotal"));
        tVenta.setRowHeight(40);
        dataVector=new AlmacenVectorListener(tProducto.getDefaultModel().getDataVector(),new Object[]{null,null,null,"g",null,0,null});
        
        
        dataVector.setStockColumn(tProducto.getColumnModel().getColumnIndex("Stock"));
        tProducto.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);  
        
        addWindowListener(new java.awt.event.WindowAdapter() 
        {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) 
            {
                new FileCollection(productos).saveData(dataVector);
            }
        });
        
        tProducto.getModel().addTableModelListener((TableModelEvent e) ->
        {
            if(e.getType()==TableEvent.DELETE_BUTTON_CLICKED && Integer.valueOf(((TableModel)e.getSource()).getValueAt(e.getFirstRow(), dataVector.stockColumn).toString()).equals(0))
            {
               ((AbstractTableModel)e.getSource()).fireTableChanged(new TableModelEvent((TableModel) e.getSource(),e.getFirstRow(),e.getFirstRow(),TableModelEvent.ALL_COLUMNS,TableEvent.CONFIRMED_DELETE));
               ((DefaultTableModel)e.getSource()).removeRow(e.getFirstRow());                                    
            }
            else if(e.getType()==TableEvent.DELETE_BUTTON_CLICKED && !Integer.valueOf(((TableModel)e.getSource()).getValueAt(e.getFirstRow(), dataVector.stockColumn).toString()).equals(0))
                JOptionPane.showMessageDialog(rootPane, "El stock del producto no es 0", "", JOptionPane.OK_OPTION);
            else if(e.getType()==TableEvent.LAST_ROW_IS_FULLFILLED)
                ((DefaultTableModel)e.getSource()).addRow(new Object[]{null,null,null,"g",null,0,null});
            
        });
        tProducto.getModel().addTableModelListener(dataVector);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tabbedPane = new javax.swing.JTabbedPane();
        pProovedores = new javax.swing.JPanel();
        tfNombre = new javax.swing.JTextField();
        lProducto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tProducto = new components.Table();
        pVerProductos = new javax.swing.JPanel();
        lTotal = new javax.swing.JLabel();
        lRecibo = new javax.swing.JLabel();
        lCambio = new javax.swing.JLabel();
        tfCambio = new javax.swing.JTextField();
        bCobrar = new javax.swing.JButton();
        tfTotal = new javax.swing.JTextField();
        tfRecibido = new components.TextField();
        lClaveProducto = new javax.swing.JLabel();
        tfClave = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tVenta = new components.Ventas();
        ;
        pCabecera = new javax.swing.JPanel();
        lNeto = new javax.swing.JLabel();
        bAñadirVenta = new javax.swing.JButton();
        bVerProductos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        tabbedPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabbedPane.setEnabled(false);

        tfNombre.setForeground(new java.awt.Color(153, 153, 153));
        tfNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                tfNombreKeyReleased(evt);
            }
        });

        lProducto.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lProducto.setText("Nombre producto:");

        tProducto.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String []
            {
                "Clave", "Nombre", "Contenido", "Unidad","Precio venta","Stock","Acción"
            })
            {

                @Override
                public void removeRow(int row)
                {
                    fireTableRowsDeleted(row, row);
                    dataVector.removeElementAt(row);
                }
            });
            jScrollPane1.setViewportView(tProducto);

            javax.swing.GroupLayout pProovedoresLayout = new javax.swing.GroupLayout(pProovedores);
            pProovedores.setLayout(pProovedoresLayout);
            pProovedoresLayout.setHorizontalGroup(
                pProovedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pProovedoresLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(pProovedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pProovedoresLayout.createSequentialGroup()
                            .addComponent(lProducto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(48, Short.MAX_VALUE))
            );
            pProovedoresLayout.setVerticalGroup(
                pProovedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pProovedoresLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addGroup(pProovedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lProducto))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE))
            );

            tabbedPane.addTab("", pProovedores);

            lTotal.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
            lTotal.setText("Total:");

            lRecibo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
            lRecibo.setText("Recibo:");

            lCambio.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
            lCambio.setText("Cambio:");

            tfCambio.setEditable(false);

            bCobrar.setText("Cobrar");
            bCobrar.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    bCobrarActionPerformed(evt);
                }
            });

            tfTotal.setEditable(false);

            tfRecibido.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    tfRecibidoActionPerformed(evt);
                }
            });

            lClaveProducto.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
            lClaveProducto.setText("Clave producto:");

            tfClave.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    tfClaveActionPerformed(evt);
                }
            });

            tVenta.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][]
                {

                },
                new String []
                {
                    "Clave", "Nombre", "Contenido", "Unidad", "Precio venta", "Cantidad", "Acción", "Subtotal"
                }
            )
            {
                boolean[] canEdit = new boolean []
                {
                    false, false, false, false, false, true, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex)
                {
                    return canEdit [columnIndex];
                }
            });
            jScrollPane2.setViewportView(tVenta);
            if (tVenta.getColumnModel().getColumnCount() > 0)
            {
                tVenta.getColumnModel().getColumn(6).setCellEditor(new TableActionCellEditor());
                tVenta.getColumnModel().getColumn(6).setCellRenderer(new TableActionCellRender());
            }

            javax.swing.GroupLayout pVerProductosLayout = new javax.swing.GroupLayout(pVerProductos);
            pVerProductos.setLayout(pVerProductosLayout);
            pVerProductosLayout.setHorizontalGroup(
                pVerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pVerProductosLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(pVerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pVerProductosLayout.createSequentialGroup()
                            .addComponent(lClaveProducto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfClave, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pVerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pVerProductosLayout.createSequentialGroup()
                                .addGroup(pVerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pVerProductosLayout.createSequentialGroup()
                                        .addComponent(lCambio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pVerProductosLayout.createSequentialGroup()
                                        .addGroup(pVerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lRecibo)
                                            .addComponent(lTotal))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pVerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bCobrar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(24, Short.MAX_VALUE))
            );
            pVerProductosLayout.setVerticalGroup(
                pVerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pVerProductosLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(pVerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lClaveProducto)
                        .addComponent(tfClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pVerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bCobrar)
                        .addComponent(lTotal))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pVerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lRecibo)
                        .addComponent(tfRecibido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pVerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lCambio)
                        .addComponent(tfCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(19, Short.MAX_VALUE))
            );

            tabbedPane.addTab("", pVerProductos);

            getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

            pCabecera.setBackground(new java.awt.Color(3, 129, 255));
            pCabecera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

            lNeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/neto2.png"))); // NOI18N

            bAñadirVenta.setBackground(new java.awt.Color(255, 161, 72));
            bAñadirVenta.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
            bAñadirVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recibir_dinero1.png"))); // NOI18N
            bAñadirVenta.setText("Añadir venta");
            bAñadirVenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
            bAñadirVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            bAñadirVenta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
            bAñadirVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            bAñadirVenta.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    bAñadirVentaActionPerformed(evt);
                }
            });

            bVerProductos.setBackground(new java.awt.Color(255, 161, 72));
            bVerProductos.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
            bVerProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos2.png"))); // NOI18N
            bVerProductos.setText("Ver productos");
            bVerProductos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
            bVerProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            bVerProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            bVerProductos.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    bVerProductosActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout pCabeceraLayout = new javax.swing.GroupLayout(pCabecera);
            pCabecera.setLayout(pCabeceraLayout);
            pCabeceraLayout.setHorizontalGroup(
                pCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pCabeceraLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(lNeto)
                    .addGap(34, 34, 34)
                    .addComponent(bVerProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(bAñadirVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(138, Short.MAX_VALUE))
            );
            pCabeceraLayout.setVerticalGroup(
                pCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pCabeceraLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pCabeceraLayout.createSequentialGroup()
                            .addGroup(pCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bVerProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(bAñadirVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pCabeceraLayout.createSequentialGroup()
                            .addComponent(lNeto, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addContainerGap())))
            );

            getContentPane().add(pCabecera, java.awt.BorderLayout.PAGE_START);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void bVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerProductosActionPerformed
        // TODO add your handling code here:
        tabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_bVerProductosActionPerformed

    private void bAñadirVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirVentaActionPerformed
        // TODO add your handling code here:
        tabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_bAñadirVentaActionPerformed
  
    private void tfClaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfClaveActionPerformed
    {//GEN-HEADEREND:event_tfClaveActionPerformed
        // TODO add your handling code here: 
        Object clave=tfClave.getText();
        int rowVector=dataVector.getRowOf(clave);
        if(rowVector==-1)
        
            JOptionPane.showMessageDialog(null, "No hay un producto cuya clave sea " + tfClave.getText() + " en la tabla Productos\nAñadelo a la tabla Productos primero");
           
        
        else
        {
            int rowVentas=tVenta.getRowOf(clave);
            if(rowVentas==-1)
                
                if(dataVector.hayStock(1,rowVector)) 
                    JOptionPane.showMessageDialog(null, "Ya no hay stock de " + dataVector.get(rowVector).get(1) + " producto");   
                else               
                    tVenta.añadirProducto(new Vector(dataVector.get(rowVector)));    
            else
            {
                System.out.println(rowVentas);
                short cantidad=Short.parseShort(tVenta.getValueAt(rowVentas, tVenta.cantidadColumn).toString());
                if(dataVector.hayStock(cantidad,rowVector))
                    tVenta.aumentarCantidad(rowVentas);
                else
                    JOptionPane.showMessageDialog(null, "Ya no hay stock de este producto");
            }
        }
        tfClave.setText("");
    }//GEN-LAST:event_tfClaveActionPerformed

    private void bCobrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bCobrarActionPerformed
    {//GEN-HEADEREND:event_bCobrarActionPerformed
        // TODO add your handling code here:     
        tfTotal.setText(String.valueOf(tVenta.calcularTotal(dataVector)));
    }//GEN-LAST:event_bCobrarActionPerformed

    private void tfRecibidoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfRecibidoActionPerformed
    {//GEN-HEADEREND:event_tfRecibidoActionPerformed
        // TODO add your handling code here:
        tfCambio.setText(String.valueOf(Float.valueOf(tfRecibido.getText())-Float.valueOf(tfTotal.getText())));
    }//GEN-LAST:event_tfRecibidoActionPerformed

    private void tfNombreKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfNombreKeyReleased
    {//GEN-HEADEREND:event_tfNombreKeyReleased
        // TODO add your handling code here:
        int nombreColumn=tProducto.getColumnModel().getColumnIndex("Nombre");
        tProducto.getDefaultModel().setRowCount(0);
        for(int row=0;row<dataVector.size()-1;row++)
            if(((String)dataVector.getValueAt(row, nombreColumn)).contains(tfNombre.getText()))            
                tProducto.getDefaultModel().addRow(new Vector(dataVector.get(row)));
        tProducto.getDefaultModel().addRow(new Vector(dataVector.get(dataVector.size()-1))); 
    }//GEN-LAST:event_tfNombreKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Light look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Administrador().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAñadirVenta;
    private javax.swing.JButton bCobrar;
    private javax.swing.JButton bVerProductos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lCambio;
    private javax.swing.JLabel lClaveProducto;
    private javax.swing.JLabel lNeto;
    private javax.swing.JLabel lProducto;
    private javax.swing.JLabel lRecibo;
    private javax.swing.JLabel lTotal;
    private javax.swing.JPanel pCabecera;
    private javax.swing.JPanel pProovedores;
    private javax.swing.JPanel pVerProductos;
    private components.Table tProducto;
    private components.Ventas tVenta;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField tfCambio;
    private javax.swing.JTextField tfClave;
    private javax.swing.JTextField tfNombre;
    private components.TextField tfRecibido;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
    AlmacenVectorListener dataVector;

    private void initProducto()
    {
        if (tProducto.getColumnModel().getColumnCount() > 0)
        {
            tProducto.getColumnModel().getColumn(1).setCellEditor(new StringEditor());
            tProducto.getColumnModel().getColumn(2).setCellEditor(new FloatEditor());
            tProducto.getColumnModel().getColumn(2).setCellRenderer(new CenterRender());
            tProducto.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(new JComboBox(new String[]{"ml","l","g","kg","pza"})));
            tProducto.getColumnModel().getColumn(3).setCellRenderer(new CenterRender());
            tProducto.getColumnModel().getColumn(4).setCellEditor(new FloatEditor());
            tProducto.getColumnModel().getColumn(4).setCellRenderer(new CenterRender());
            tProducto.getColumnModel().getColumn(5).setCellRenderer(new CenterRender());
            
        }
    }
}
